# The host names don't matter here because the playbook is supposed to be run directly on the machines with a local connection.
# Only the groups are important as they determine how the machine gets configured and what gets installed.
[mvhs]
mvhs1

[work]
work1  # WSL box on my AMC

[home]
home1  # Lima box on my MacBook
malbox  # 2nd, disposable Lima box on my MacBook for malware analysis
