# change prefix to Ctrl+/
unbind C-b
set -g prefix C-_
bind C-_ send-prefix

unbind c
unbind '"'
unbind %
bind n new-window
bind | split-window -h
bind _ split-window -v

bind -n C-Left previous-window
bind -n C-Right next-window
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

set -g mouse on
set -g word-separators " ='\"()[]{}<>"

# right-click to paste the internal tmux buffer
unbind -n MouseDown3Pane
bind -n MouseDown3Pane paste-buffer
